# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-28 02:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name=b'Nome')),
                ('email', models.CharField(max_length=50, verbose_name=b'E-mail')),
                ('mensagem', models.TextField(verbose_name=b'Descri\xc3\xa7\xc3\xa3o')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name=b'Criado em')),
            ],
            options={
                'ordering': ['name'],
                'verbose_name': 'Contato',
                'verbose_name_plural': 'Contatos',
            },
        ),
    ]
